# -*- coding: utf-8 -*-
"""capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Soha-Waseem/FlyRank_ML_Week1/blob/main/work/notebooks/capstone.ipynb

# Capstone — mirrors your deployed research paper

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Soha-Waseem/FlyRank_ML_Week1/blob/main/work/notebooks/capstone.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

# Predicting Content Performance Decline for Search Intelligence

## Abstract

This study asks whether historical search, traffic, engagement, and content signals can help identify content items that are likely to experience a meaningful decline in next-month impressions.

Using the FlyRank internship warehouse, I constructed a monthly content-level dataset and defined decline as a 20% or greater reduction in impressions in the following month.

I compared a constant-probability baseline with leakage-safe Logistic Regression and Random Forest models using a time-based train/test split.

The leakage-safe Random Forest achieved a ROC-AUC of 0.5554 and Average Precision of 0.6386 compared with a ROC-AUC of 0.5000 for the baseline.

The resulting ranking is therefore presented as a directional decision-support tool for prioritizing content review rather than as a causal prediction of future search performance.

# 1. Question

## Research Question

Can historical search, traffic, engagement, and content characteristics help identify content items that are likely to experience a meaningful decline in next-month impressions?

## Decision Supported

The objective is to support content prioritization.

Instead of treating every content item equally, the analysis produces a ranked list of content observations by estimated decline risk. This can help a content team decide which pages should receive earlier review.

The output is intended as directional decision support. It does not establish that any particular content change will cause improved search performance.

# 2. Data

The analysis uses the FlyRank ML Internship warehouse release provided for the internship.

The primary sources used were:

- `fact_content_daily_performance`
- `dim_content`

Daily performance data was aggregated to a monthly content-level representation before modeling.

The available daily performance data covers 2025-01-27 through 2026-06-30, with 520 unique reporting dates, 70 clients, and 427,292 content items.

The resulting monthly modeling table contains 2,748,610 observations covering January 2025 through June 2026.

For the prediction task, an observation is eligible for labeling when a subsequent month is available. This produced 797,753 eligible observations.

A decline was defined as a 20% or greater decrease in impressions in the following month.

The final modeling dataset contained 797,753 observations:

- 319,754 declining observations
- 477,999 non-declining observations
- 40.08% decline rate among eligible observations

Client names, domains, private queries, credentials, and raw exports were excluded from the public analysis.
"""

import os
import getpass
import duckdb

HF_TOKEN = os.environ.get("HF_TOKEN")

if not HF_TOKEN:
    try:
        from google.colab import userdata
        HF_TOKEN = userdata.get("HF_TOKEN")
    except Exception:
        pass

if not HF_TOKEN:
    HF_TOKEN = getpass.getpass("Paste HF token: ")

con = duckdb.connect()

con.execute(
    f"CREATE OR REPLACE SECRET hf "
    f"(TYPE huggingface, TOKEN '{HF_TOKEN}')"
)

REL = "hf://datasets/FlyRank/internship-warehouse"

TABLES = {
    "dim_clients":
        f"read_parquet('{REL}/dim_clients.parquet')",

    "dim_content":
        f"read_parquet('{REL}/dim_content.parquet')",

    "fact_daily":
        f"read_parquet('{REL}/fact_content_daily_performance/**/*.parquet')",

    "fact_daily_sample":
        f"read_parquet('{REL}/fact_content_daily_performance_sample.parquet')",

    "fact_query_90d":
        f"read_parquet('{REL}/fact_content_query_90d.parquet')",
}

for name, src in TABLES.items():
    n = con.sql(
        f"SELECT COUNT(*) FROM {src}"
    ).fetchone()[0]

    print(f"{name:22} {n:>12,} rows")

for name, src in TABLES.items():
    print("\n" + "=" * 80)
    print(f"SCHEMA: {name}")
    print("=" * 80)

    con.sql(
        f"DESCRIBE SELECT * FROM {src}"
    ).show()

for name, src in TABLES.items():

    print("\n" + "=" * 80)
    print(f"ALL COLUMNS: {name}")
    print("=" * 80)

    schema = con.sql(
        f"DESCRIBE SELECT * FROM {src}"
    ).fetchall()

    for i, row in enumerate(schema, start=1):
        print(f"{i:2}. {row[0]:40} {row[1]}")

fact = TABLES["fact_daily"]

con.sql(f"""
    SELECT
        MIN(report_date) AS earliest_date,
        MAX(report_date) AS latest_date,
        COUNT(DISTINCT report_date) AS unique_dates,
        COUNT(DISTINCT client_hash_id) AS clients,
        COUNT(DISTINCT content_hash_id) AS content
    FROM {fact}
""").show()

con.sql(f"""
    SELECT
        month,
        MIN(report_date) AS min_date,
        MAX(report_date) AS max_date,
        COUNT(*) AS rows,
        COUNT(DISTINCT client_hash_id) AS clients,
        COUNT(DISTINCT content_hash_id) AS content
    FROM {fact}
    GROUP BY month
    ORDER BY month
""").show()

query90 = TABLES["fact_query_90d"]

con.sql(f"""
    SELECT
        MIN(window_start) AS earliest_window,
        MAX(window_end) AS latest_window,
        COUNT(*) AS rows,
        COUNT(DISTINCT client_hash_id) AS clients,
        COUNT(DISTINCT content_hash_id) AS content
    FROM {query90}
""").show()

"""## 1. Question

### Research question

Can historical search performance, traffic, engagement, and content characteristics identify content items that are likely to experience future performance decline?

### Decision supported

The goal is to support a content-refresh prioritization decision. Rather than treating every page equally, the analysis produces a ranked list of content items that show higher estimated risk of future decline and therefore may warrant review or refresh.

This is a decision-support system, not a causal model. A high score indicates that an item resembles historical observations associated with decline; it does not prove that the content will decline or that refreshing it will cause performance to improve.

### ML task

This capstone uses binary classification to estimate the probability of future performance decline. The resulting probabilities are then used as an opportunity/risk ranking for content review.
"""



"""## 2. Data

This project uses the FlyRank internship warehouse release hosted on Hugging Face.

### Tables used

The primary analysis uses:

- `fact_daily` — daily content-level search and traffic performance.
- `dim_content` — content metadata and content characteristics.

The `fact_query_90d` table is available in the warehouse and may be used for supporting query-level features if those features pass the temporal leakage checks.

### Date coverage

The `fact_daily` table covers:

**2025-01-27 through 2026-06-30**

The warehouse contains observations for 70 clients and 427,292 distinct content items.

The `fact_query_90d` table covers:

**2026-04-02 through 2026-06-30**

and therefore provides a much shorter historical window than `fact_daily`. For this reason, it is not assumed to be a required core feature source.

### Public-safe handling

The analysis uses pseudonymized client and content identifiers. No client names, domains, private search queries, credentials, or raw exports are exposed in the final research paper.

### Exclusions

Deleted or unpublished content is excluded from the primary modeling dataset because the objective is to prioritize content that is currently eligible for review.

Features derived from future observations, label-derived fields, client-identifying information, and other fields that fail leakage checks are excluded from model training.
"""

import os
import getpass
import duckdb
import pandas as pd
import numpy as np

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    classification_report,
    confusion_matrix
)
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

fact = TABLES["fact_daily"]
content = TABLES["dim_content"]

coverage = con.sql(f"""
    SELECT
        MIN(report_date) AS earliest_date,
        MAX(report_date) AS latest_date,
        COUNT(DISTINCT report_date) AS unique_dates,
        COUNT(DISTINCT client_hash_id) AS clients,
        COUNT(DISTINCT content_hash_id) AS content_items
    FROM {fact}
""").df()

coverage

monthly_sql = f"""
WITH monthly AS (
    SELECT
        DATE_TRUNC('month', report_date) AS month_date,
        client_hash_id,
        content_hash_id,

        SUM(gsc_impressions) AS impressions,
        SUM(gsc_clicks) AS clicks,
        AVG(gsc_avg_position) AS avg_position,

        SUM(ga4_pageviews) AS pageviews,
        SUM(ga4_sessions) AS sessions,
        SUM(ga4_users) AS users,
        SUM(ga4_engaged_sessions) AS engaged_sessions,
        SUM(ga4_total_engagement_sec) AS engagement_seconds,

        SUM(sessions_organic) AS organic_sessions,
        SUM(sessions_direct) AS direct_sessions,
        SUM(sessions_referral) AS referral_sessions,
        SUM(sessions_social) AS social_sessions,
        SUM(sessions_paid) AS paid_sessions,
        SUM(sessions_ai) AS ai_sessions,

        SUM(scroll_events) AS scroll_events

    FROM {fact}

    GROUP BY
        DATE_TRUNC('month', report_date),
        client_hash_id,
        content_hash_id
)

SELECT
    m.*,

    CASE
        WHEN impressions > 0
        THEN clicks::DOUBLE / impressions
        ELSE 0
    END AS ctr,

    CASE
        WHEN sessions > 0
        THEN engaged_sessions::DOUBLE / sessions
        ELSE 0
    END AS engagement_rate,

    c.content_type,
    c.search_volume,
    c.competition,
    c.competition_level,
    c.cpc,
    c.main_intent,
    c.backlinks,
    c.category_count,
    c.char_count,
    c.word_count,

    c.content_created_date,
    c.content_updated_date,
    c.last_optimized_date,
    c.optimization_eligible_date,

    c.is_published,
    c.is_deleted

FROM monthly m

LEFT JOIN {content} c
    ON m.client_hash_id = c.client_hash_id
    AND m.content_hash_id = c.content_hash_id

WHERE
    c.is_deleted = FALSE
    AND c.is_published = TRUE
"""

monthly_df = con.sql(monthly_sql).df()

print("Monthly modeling table:", monthly_df.shape)

monthly_df.head()

"""## 3. Methodology

The modeling unit is one content item at a monthly prediction snapshot.

For each content item and prediction month, features are calculated using information available during that month. The target is calculated from the following month so that the model is evaluated on a future outcome rather than on the same observations used to construct its features.

The primary outcome is `is_declining_label`, where 1 indicates that the content experienced a meaningful decline in search performance in the following month and 0 indicates that it did not meet the decline rule.

Historical search performance, traffic, engagement, and content characteristics are considered as candidate predictors.

Label-derived fields and future-period measurements are excluded from the feature vector. Content identifiers are retained only for grouping and final ranking and are not used as predictive features.

The validation design preserves temporal ordering. Earlier observations are used for model development and later observations are held out for evaluation. This is intended to provide a more realistic estimate of performance on future content observations.

Model performance will be compared against a simple baseline using the same evaluation data. ROC-AUC is the primary discrimination metric, with average precision also reported because the proportion of declining content may be imbalanced.

The analysis is observational and decision-support oriented. Model scores indicate similarity to historical patterns associated with decline; they do not establish causality or prove that refreshing a page will improve its performance.


### **Temporal validation design**

The labeled dataset contains observations from January 2025 through May 2026. June 2026 is excluded from supervised evaluation because no July observation exists to construct the future outcome.

A chronological holdout is used rather than a random split. Observations from January 2025 through March 2026 form the training period, while April 2026 through May 2026 form the held-out test period.

This design evaluates whether patterns learned from earlier observations remain useful for later observations. The test period is never used to fit preprocessing steps or model parameters.

The observed decline rate varies over time. In particular, the rate increases during the final months of the available labeled period. This temporal variation is treated as part of the evaluation context rather than interpreted as evidence of a causal change.
"""

# Check monthly coverage available for next-month labeling

monthly_df["month_date"] = pd.to_datetime(monthly_df["month_date"])

available_months = sorted(
    monthly_df["month_date"].dropna().unique()
)

print("First month:", available_months[0])
print("Last month:", available_months[-1])
print("Number of months:", len(available_months))

print("\nLast 6 months:")
for m in available_months[-6:]:
    print(pd.Timestamp(m).strftime("%Y-%m"))

# ============================================================
# FIXED FUTURE DECLINE LABEL
# ============================================================

# Remove the incorrect label
df = df.drop(columns=["is_declining_label"], errors="ignore")

# A row is eligible for classification when:
# 1. A true next calendar month exists
# 2. Current month has at least MIN_IMPRESSIONS
# 3. Next-month impressions are available

df["label_eligible"] = (
    df["has_next_month"]
    & (df["impressions"] >= MIN_IMPRESSIONS)
    & df["next_month_impressions"].notna()
)

# Binary target:
# 1 = next-month impressions declined by at least 20%
# 0 = otherwise
# NaN = not eligible because a valid future outcome is unavailable

df["is_declining_label"] = np.nan

df.loc[df["label_eligible"], "is_declining_label"] = (
    df.loc[
        df["label_eligible"],
        "impression_change_pct"
    ] <= -DECLINE_THRESHOLD
).astype(int)

print("Total monthly observations:", len(df))

print(
    "Eligible labeled observations:",
    int(df["label_eligible"].sum())
)

print(
    "Declining:",
    int((df["is_declining_label"] == 1).sum())
)

print(
    "Not declining:",
    int((df["is_declining_label"] == 0).sum())
)

print(
    "Missing / excluded:",
    int(df["is_declining_label"].isna().sum())
)

print(
    "Decline rate among eligible observations:",
    round(
        df.loc[
            df["label_eligible"],
            "is_declining_label"
        ].mean() * 100,
        2
    ),
    "%"
)

# ============================================================
# LABEL SENSITIVITY CHECK
# ============================================================

labeled = df[
    df["has_next_month"]
    & (df["impressions"] >= MIN_IMPRESSIONS)
    & df["next_month_impressions"].notna()
].copy()

for threshold in [0.10, 0.15, 0.20, 0.25, 0.30]:

    label = (
        labeled["impression_change_pct"]
        <= -threshold
    )

    print(
        f"{int(threshold * 100):>2}% decline threshold → "
        f"{label.mean() * 100:6.2f}% declining "
        f"({label.sum():,} / {len(label):,})"
    )

"""### Label definition

The prediction unit is one content item at a monthly snapshot.

A labeled observation requires a valid following calendar month and at least 50 impressions in the prediction month. The target `is_declining_label` is 1 when the following month's impressions are at least 20% lower than the prediction month's impressions. Otherwise it is 0.

The final month of the dataset cannot receive a label because no following month is available.

A 20% threshold was selected after a sensitivity check across 10%, 15%, 20%, 25%, and 30% decline thresholds. At the selected threshold, 40.08% of eligible observations were labeled declining.

### Leakage prevention

The model may only use information available during the prediction month. The following-month measurements used to create `is_declining_label` are never included as model features.

The fields `next_month_impressions`, `next_month_clicks`, `next_month_sessions`, `next_month_date`, `expected_next_month`, `has_next_month`, `impression_change_pct`, and `is_declining_label` are excluded from the feature vector.

Content and client identifiers are retained for grouping, temporal checks, and final recommendation output but are not used as predictive features.
"""

# ============================================================
# LEAKAGE CHECK — FUTURE / LABEL-DERIVED COLUMNS
# ============================================================

future_or_label_columns = [
    "next_month_impressions",
    "next_month_clicks",
    "next_month_sessions",
    "next_month_date",
    "expected_next_month",
    "has_next_month",
    "impression_change_pct",
    "is_declining_label",
    "label_eligible"
]

print("Leakage / label-derived columns found:")

for col in future_or_label_columns:
    print(f"{col:30} -> {col in df.columns}")

# ============================================================
# CANDIDATE FEATURE VECTOR
# ============================================================

candidate_features = [
    # Search performance
    "impressions",
    "clicks",
    "ctr",
    "avg_position",

    # Traffic
    "pageviews",
    "sessions",
    "users",
    "engaged_sessions",
    "engagement_seconds",

    # Traffic sources
    "organic_sessions",
    "direct_sessions",
    "referral_sessions",
    "social_sessions",
    "paid_sessions",
    "ai_sessions",

    # Engagement
    "scroll_events",
    "engagement_rate",

    # Search demand / competition
    "search_volume",
    "competition",
    "cpc",
    "backlinks",
    "category_count",

    # Content characteristics
    "char_count",
    "word_count",
    "content_type",
    "competition_level",
    "main_intent"
]

missing_features = [
    col for col in candidate_features
    if col not in df.columns
]

print("Candidate features:", len(candidate_features))

if missing_features:
    print("\nMISSING FEATURES:")
    for col in missing_features:
        print(" -", col)
else:
    print("All candidate features exist.")

# ============================================================
# FEATURE MISSINGNESS
# ============================================================

feature_audit = pd.DataFrame({
    "feature": candidate_features,
    "dtype": [
        df[col].dtype
        for col in candidate_features
    ],
    "missing_count": [
        df[col].isna().sum()
        for col in candidate_features
    ],
    "missing_pct": [
        df[col].isna().mean() * 100
        for col in candidate_features
    ],
    "unique_values": [
        df[col].nunique(dropna=True)
        for col in candidate_features
    ]
})

feature_audit.sort_values(
    "missing_pct",
    ascending=False
)

# ============================================================
# CAPSTONE — REMOVE TEMPORALLY LEAKED FEATURES
# ============================================================

leaked_date_features = [
    "content_age_days",
    "days_since_update",
    "days_since_optimization",
    "content_created_date",
    "content_updated_date",
    "last_optimized_date",
    "optimization_eligible_date"
]

safe_numeric_features = [
    col for col in numeric_features
    if col not in [
        "content_age_days",
        "days_since_update",
        "days_since_optimization"
    ]
]

safe_categorical_features = categorical_features.copy()

safe_final_features = (
    safe_numeric_features +
    safe_categorical_features
)

print("Original numeric features:", len(numeric_features))
print("Safe numeric features:", len(safe_numeric_features))
print("Categorical features:", len(safe_categorical_features))
print("Total safe features:", len(safe_final_features))

print("\nRemoved date-derived features:")
for feature in [
    "content_age_days",
    "days_since_update",
    "days_since_optimization"
]:
    print("-", feature)

# ============================================================
# FINAL FEATURE SANITY CHECK
# ============================================================

print("Feature columns present:")

missing_final_features = [
    col for col in final_features
    if col not in model_df.columns
]

if missing_final_features:
    print("MISSING:")
    for col in missing_final_features:
        print(" -", col)
else:
    print("All final features are present.")

print("\nTarget values:")
print(
    sorted(
        model_df["is_declining_label"]
        .dropna()
        .unique()
    )
)

print("\nRows:", len(model_df))
print("Columns used:", len(final_features))

# ============================================================
# TEMPORAL LABEL COVERAGE
# ============================================================

month_summary = (
    model_df
    .groupby("month_date")
    .agg(
        observations=("is_declining_label", "size"),
        declining=("is_declining_label", "sum")
    )
    .reset_index()
)

month_summary["decline_rate"] = (
    month_summary["declining"]
    / month_summary["observations"]
)

month_summary

# ============================================================
# TEMPORAL TRAIN / TEST SPLIT
# ============================================================

TRAIN_END = pd.Timestamp("2026-03-01")

train_df = model_df[
    model_df["month_date"] <= TRAIN_END
].copy()

test_df = model_df[
    model_df["month_date"] > TRAIN_END
].copy()

print("TRAIN")
print(
    train_df["month_date"].min(),
    "to",
    train_df["month_date"].max()
)
print("Rows:", len(train_df))
print(
    "Decline rate:",
    round(train_df["is_declining_label"].mean() * 100, 2),
    "%"
)

print("\nTEST")
print(
    test_df["month_date"].min(),
    "to",
    test_df["month_date"].max()
)
print("Rows:", len(test_df))
print(
    "Decline rate:",
    round(test_df["is_declining_label"].mean() * 100, 2),
    "%"
)

# ============================================================
# SAFE TRAIN / TEST FEATURES
# ============================================================

X_train_safe = train_df[safe_final_features]
X_test_safe = test_df[safe_final_features]

print("X_train:", X_train_safe.shape)
print("X_test:", X_test_safe.shape)

# ============================================================
# LEAKAGE-SAFE PREPROCESSOR
# ============================================================

safe_preprocessor = ColumnTransformer(
    transformers=[
        (
            "numeric",
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler())
            ]),
            safe_numeric_features
        ),
        (
            "categorical",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("encoder", OneHotEncoder(handle_unknown="ignore"))
            ]),
            safe_categorical_features
        )
    ]
)

print("Leakage-safe preprocessing pipeline created.")
print("Numeric features:", len(safe_numeric_features))
print("Categorical features:", len(safe_categorical_features))
print("Total features:", len(safe_final_features))

# ============================================================
# LEAKAGE-SAFE LOGISTIC REGRESSION
# ============================================================

safe_logistic_model = Pipeline(
    steps=[
        ("preprocessor", safe_preprocessor),
        (
            "model",
            LogisticRegression(
                max_iter=2000,
                class_weight="balanced",
                random_state=42
            )
        )
    ]
)

print("Training leakage-safe Logistic Regression...")

safe_logistic_model.fit(
    X_train_safe,
    y_train
)

print("Training complete.")

# ============================================================
# EVALUATE LEAKAGE-SAFE LOGISTIC REGRESSION
# ============================================================

safe_logistic_probabilities = (
    safe_logistic_model
    .predict_proba(X_test_safe)[:, 1]
)

safe_logistic_roc_auc = roc_auc_score(
    y_test,
    safe_logistic_probabilities
)

safe_logistic_ap = average_precision_score(
    y_test,
    safe_logistic_probabilities
)

print(
    "Leakage-safe Logistic Regression ROC-AUC:",
    round(safe_logistic_roc_auc, 4)
)

print(
    "Leakage-safe Logistic Regression Average Precision:",
    round(safe_logistic_ap, 4)
)

print(
    "ROC-AUC improvement over baseline:",
    round(
        safe_logistic_roc_auc - baseline_roc_auc,
        4
    )
)

# ============================================================
# LEAKAGE-SAFE RANDOM FOREST
# ============================================================

safe_random_forest = Pipeline(
    steps=[
        ("preprocessor", safe_preprocessor),
        (
            "model",
            RandomForestClassifier(
                n_estimators=150,
                max_depth=12,
                min_samples_leaf=20,
                class_weight="balanced",
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)

print("Training leakage-safe Random Forest...")

safe_random_forest.fit(
    X_train_safe,
    y_train
)

print("Training complete.")

# ============================================================
# EVALUATE LEAKAGE-SAFE RANDOM FOREST
# ============================================================

safe_rf_probabilities = (
    safe_random_forest
    .predict_proba(X_test_safe)[:, 1]
)

safe_rf_roc_auc = roc_auc_score(
    y_test,
    safe_rf_probabilities
)

safe_rf_ap = average_precision_score(
    y_test,
    safe_rf_probabilities
)

print(
    "Leakage-safe Random Forest ROC-AUC:",
    round(safe_rf_roc_auc, 4)
)

print(
    "Leakage-safe Random Forest Average Precision:",
    round(safe_rf_ap, 4)
)

print(
    "ROC-AUC improvement over baseline:",
    round(
        safe_rf_roc_auc - baseline_roc_auc,
        4
    )
)

# ============================================================
# CAPSTONE — FINAL MODEL COMPARISON
# ============================================================

results = pd.DataFrame({
    "Model": [
        "Baseline",
        "Scaled Logistic Regression",
        "Random Forest"
    ],
    "ROC-AUC": [
        baseline_roc_auc,
        scaled_logistic_roc_auc,
        rf_roc_auc
    ],
    "Average Precision": [
        baseline_ap,
        scaled_logistic_ap,
        rf_ap
    ]
})

results["ROC-AUC"] = results["ROC-AUC"].round(4)
results["Average Precision"] = results["Average Precision"].round(4)

results

# ============================================================
# MODEL COMPARISON CHART
# ============================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(9, 5))

plt.bar(
    results["Model"],
    results["ROC-AUC"]
)

plt.ylabel("ROC-AUC")
plt.xlabel("Model")
plt.title("Model Performance on April–May 2026 Holdout")

plt.ylim(0.45, 0.65)
plt.xticks(rotation=15)

for i, value in enumerate(results["ROC-AUC"]):
    plt.text(
        i,
        value + 0.005,
        f"{value:.3f}",
        ha="center"
    )

plt.tight_layout()
plt.show()

"""## 4. Results (vs baseline)

### Model comparison

Three approaches were evaluated on the same chronological holdout covering April–May 2026: a prevalence baseline, scaled Logistic Regression, and Random Forest.

The baseline achieved a ROC-AUC of 0.5000 and Average Precision of 0.6005. Scaled Logistic Regression improved these values to 0.5561 and 0.6263 respectively. Random Forest performed best, achieving a ROC-AUC of 0.5960 and Average Precision of 0.6669.

These results indicate that the Random Forest captured limited but measurable ranking signal beyond the baseline. The result should be interpreted as decision-support evidence rather than a highly accurate prediction system. The substantially higher decline rate in the test period compared with training also indicates temporal distribution shift, which limits how broadly the result should be generalized.
"""

# ============================================================
# FINAL MODEL — FEATURE IMPORTANCE
# ============================================================

final_rf_preprocessor = (
    safe_random_forest.named_steps["preprocessor"]
)

final_rf_model = (
    safe_random_forest.named_steps["model"]
)

feature_names = (
    final_rf_preprocessor
    .get_feature_names_out()
)

importances = final_rf_model.feature_importances_

final_feature_importance = (
    pd.DataFrame({
        "feature": feature_names,
        "importance": importances
    })
    .sort_values(
        "importance",
        ascending=False
    )
    .reset_index(drop=True)
)

final_feature_importance.head(20)

# ============================================================
# CAPSTONE — DATE FEATURE TEMPORAL LEAKAGE CHECK
# ============================================================

date_checks = {}

for col in [
    "content_created_date",
    "content_updated_date",
    "last_optimized_date",
    "optimization_eligible_date"
]:
    if col in model_df.columns:
        future_count = (
            model_df[col] > model_df["month_date"]
        ).sum()

        date_checks[col] = {
            "future_dated_rows": int(future_count),
            "future_dated_pct": round(
                future_count / len(model_df) * 100,
                4
            )
        }

pd.DataFrame(date_checks).T

# ============================================================
# CHECK DATE-BASED FEATURE VALIDITY
# ============================================================

for col in [
    "content_updated_date",
    "last_optimized_date"
]:
    future_mask = (
        model_df[col].notna()
        & (model_df[col] > model_df["month_date"])
    )

    print("\n", col)
    print("Future-dated observations:", future_mask.sum())

    if future_mask.sum() > 0:
        print(
            "WARNING: future information may be entering the model."
        )
    else:
        print(
            "PASS: no future dates detected."
        )

# ============================================================
# REMOVE TEMPORALLY LEAKED FEATURES
# ============================================================

safe_numeric_features = [
    col for col in numeric_features
    if col not in [
        "content_age_days",
        "days_since_update",
        "days_since_optimization"
    ]
]

safe_categorical_features = categorical_features.copy()

safe_final_features = (
    safe_numeric_features +
    safe_categorical_features
)

print("Original features:", len(final_features))
print("Safe features:", len(safe_final_features))

print("\nRemoved:")
print("- content_age_days")
print("- days_since_update")
print("- days_since_optimization")

# ============================================================
# CAPSTONE — RANK CONTENT BY PREDICTED DECLINE RISK
# ============================================================

recommendations = test_df.copy()

recommendations["decline_risk"] = safe_rf_probabilities

recommendations = recommendations.sort_values(
    "decline_risk",
    ascending=False
).reset_index(drop=True)

recommendations["risk_rank"] = (
    recommendations.index + 1
)

print("Ranked recommendations:", len(recommendations))

recommendations[
    [
        "risk_rank",
        "content_hash_id",
        "decline_risk",
        "ctr",
        "avg_position",
        "clicks",
        "impressions",
        "word_count"
    ]
].head(20)

# ============================================================
# RISK BANDS
# ============================================================

recommendations["risk_band"] = pd.cut(
    recommendations["decline_risk"],
    bins=[0, 0.33, 0.66, 1.0],
    labels=[
        "Lower risk",
        "Medium risk",
        "Higher risk"
    ],
    include_lowest=True
)

print(
    recommendations["risk_band"]
    .value_counts()
    .sort_index()
)

# ============================================================
# REASON CODES
# ============================================================

def generate_reason(row):

    reasons = []

    if pd.notna(row["ctr"]) and row["ctr"] < 0.5:
        reasons.append("low_ctr")

    if pd.notna(row["avg_position"]) and row["avg_position"] > 10:
        reasons.append("weaker_search_position")

    if (
        pd.notna(row["impressions"])
        and row["impressions"] > 0
        and pd.notna(row["clicks"])
        and row["clicks"] == 0
    ):
        reasons.append("impressions_without_clicks")

    if pd.notna(row["word_count"]) and row["word_count"] < 500:
        reasons.append("short_content")

    if (
        pd.notna(row["scroll_events"])
        and row["scroll_events"] == 0
    ):
        reasons.append("low_scroll_activity")

    if not reasons:
        reasons.append("model_ranked_high_risk")

    return ", ".join(reasons[:3])


recommendations["reason_codes"] = (
    recommendations
    .apply(generate_reason, axis=1)
)

recommendations[
    [
        "risk_rank",
        "content_hash_id",
        "decline_risk",
        "risk_band",
        "reason_codes"
    ]
].head(20)

# ============================================================
# CAPSTONE — ACTION PLAYBOOK
# Fast vectorized version
# ============================================================

import numpy as np
import pandas as pd

# Default action
recommendations["recommended_action"] = "Monitor and review"

# Higher-risk content
high_risk = recommendations["risk_band"].eq("Higher risk")

# Specific reason-based actions
low_ctr = recommendations["reason_codes"].fillna("").str.contains(
    "low_ctr", regex=False
)

weak_position = recommendations["reason_codes"].fillna("").str.contains(
    "weaker_search_position", regex=False
)

low_scroll = recommendations["reason_codes"].fillna("").str.contains(
    "low_scroll_activity", regex=False
)

impressions_no_clicks = recommendations["reason_codes"].fillna("").str.contains(
    "impressions_without_clicks", regex=False
)

# Assign actions in priority order
recommendations.loc[
    high_risk & low_ctr,
    "recommended_action"
] = "Review title and search snippet"

recommendations.loc[
    high_risk & weak_position & ~low_ctr,
    "recommended_action"
] = "Review content relevance and search positioning"

recommendations.loc[
    high_risk & low_scroll & ~low_ctr & ~weak_position,
    "recommended_action"
] = "Review content structure and engagement"

recommendations.loc[
    high_risk & impressions_no_clicks & ~low_ctr & ~weak_position,
    "recommended_action"
] = "Review search-result targeting and metadata"

print("Action playbook generated successfully.")
print()
print(recommendations["recommended_action"].value_counts())

# ============================================================
# HIGH-RISK ACTION SUMMARY
# ============================================================

high_risk_actions = (
    recommendations[
        recommendations["risk_band"] == "Higher risk"
    ]
    .groupby("recommended_action")
    .size()
    .reset_index(name="content_count")
    .sort_values("content_count", ascending=False)
)

high_risk_actions

# ============================================================
# PAPER-READY RECOMMENDATION SUMMARY
# ============================================================

total_test = len(recommendations)

summary = {
    "test_observations": total_test,
    "higher_risk": int(
        (recommendations["risk_band"] == "Higher risk").sum()
    ),
    "medium_risk": int(
        (recommendations["risk_band"] == "Medium risk").sum()
    ),
    "lower_risk": int(
        (recommendations["risk_band"] == "Lower risk").sum()
    )
}

print("CAPSTONE RECOMMENDATION SUMMARY")
print("=" * 50)

for key, value in summary.items():
    print(f"{key}: {value:,}")

print("\nHIGH-RISK ACTIONS")
print("=" * 50)

print(high_risk_actions.to_string(index=False))

"""## 5. Limitations

This analysis is a decision-support model rather than a causal study.

The target is defined as a 20% decline in next-month impressions, so the model identifies patterns associated with this operational definition of decline rather than an independently observed concept of content quality.

The model was evaluated using a time-based split, with earlier observations used for training and later observations used for testing. This is more realistic than a random split, but performance may change when applied to a different future period.

The leakage audit identified future-dated content fields, so date-derived features such as content age, days since update, and days since optimization were removed from the final model.

The leakage-safe Random Forest achieved a ROC-AUC of 0.5554 compared with the 0.5000 baseline. This is a measurable improvement, but it is modest. The model should therefore be used to prioritize review rather than automatically decide which content should be changed.

The results show associations in the available data. They do not prove that changing a title, updating content, improving engagement, or changing another feature will cause search performance to improve.

The ranked recommendations are therefore directional and should be validated by a content team before action.
"""



"""## 6. Ranked recommendations

The final action playbook ranks test-period content by predicted probability of decline. The ranking is intended to help content teams prioritize limited review capacity.

The highest-risk items should be reviewed first. Reason codes provide a simple explanation of the observed signals contributing to each recommendation.

### Recommended action framework

1. **Review title and search snippet**
   
   Prioritize higher-risk content showing low CTR. These pages receive impressions but capture relatively few clicks, making metadata and search-result targeting reasonable areas for review.

2. **Review content relevance and search positioning**
   
   Content showing weaker average search position should be reviewed for relevance, coverage, and alignment with the search intent represented by its available signals.

3. **Review content structure and engagement**
   
   Pages showing low scroll activity should be reviewed for structure, readability, content organization, and engagement opportunities.

4. **Review search-result targeting and metadata**
   
   Pages with impressions but very few clicks should be reviewed for whether the search result clearly communicates the page's value and intent.

5. **Monitor lower-risk content**
   
   Lower-risk content does not require immediate intervention based on this model. It can remain in a monitoring queue and be reassessed as new performance data becomes available.

These recommendations are decision-support actions derived from observed model signals. They should not be interpreted as evidence that any particular change will cause improved search performance.
"""



"""## 7. Artifacts the paper embeds

*Generate/collect the charts and tables your deployed page will show.*
"""

print("Available dataframe variables:")

for name, obj in list(globals().items()):
    if hasattr(obj, "shape") and hasattr(obj, "columns"):
        print(f"{name}: {obj.shape}")

# ============================================================
# CAPSTONE — SECTION 7: PAPER ARTIFACTS
# ============================================================

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. Model comparison table
# ------------------------------------------------------------

model_results = pd.DataFrame({
    "Model": [
        "Baseline",
        "Leakage-safe Logistic Regression",
        "Leakage-safe Random Forest"
    ],
    "ROC-AUC": [
        0.5000,
        0.5549,
        0.5554
    ],
    "Average Precision": [
        0.6005,
        0.6289,
        0.6386
    ]
})

print("MODEL COMPARISON")
display(model_results)


# ------------------------------------------------------------
# 2. ROC-AUC comparison chart
# ------------------------------------------------------------

plt.figure(figsize=(9, 5))

plt.bar(
    model_results["Model"],
    model_results["ROC-AUC"]
)

plt.axhline(
    0.5,
    linestyle="--",
    label="Random baseline"
)

plt.ylabel("ROC-AUC")
plt.title("Model Performance Compared with Baseline")
plt.xticks(rotation=20, ha="right")
plt.legend()
plt.tight_layout()

plt.savefig(
    "model_comparison_roc_auc.png",
    dpi=200,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 3. Feature importance chart
# ------------------------------------------------------------

# Use the final leakage-safe feature importance table
fi_plot = final_feature_importance.copy()

# Remove preprocessing prefixes if present
fi_plot["feature"] = (
    fi_plot["feature"]
    .astype(str)
    .str.replace("numeric__", "", regex=False)
    .str.replace("categorical__", "", regex=False)
)

fi_plot = fi_plot.sort_values(
    "importance",
    ascending=True
).tail(15)

plt.figure(figsize=(9, 7))

plt.barh(
    fi_plot["feature"],
    fi_plot["importance"]
)

plt.xlabel("Feature importance")
plt.title("Top Features in the Leakage-safe Random Forest")
plt.tight_layout()

plt.savefig(
    "feature_importance.png",
    dpi=200,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 4. Observed decline rate over time
# ------------------------------------------------------------

monthly_results = (
    model_df
    .groupby("month_date")
    .agg(
        observations=("is_declining_label", "size"),
        declining=("is_declining_label", "sum")
    )
    .reset_index()
)

monthly_results["decline_rate"] = (
    monthly_results["declining"] /
    monthly_results["observations"]
)

print("MONTHLY DECLINE RATE")
display(monthly_results)


plt.figure(figsize=(10, 5))

plt.plot(
    monthly_results["month_date"],
    monthly_results["decline_rate"],
    marker="o"
)

plt.ylabel("Decline rate")
plt.xlabel("Month")
plt.title("Observed Decline Rate Over Time")
plt.xticks(rotation=45)
plt.tight_layout()

plt.savefig(
    "decline_rate_over_time.png",
    dpi=200,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 5. Risk-band distribution
# ------------------------------------------------------------

risk_counts = (
    recommendations["risk_band"]
    .value_counts()
    .reindex(
        ["Lower risk", "Medium risk", "Higher risk"],
        fill_value=0
    )
)

risk_distribution = risk_counts.reset_index()
risk_distribution.columns = [
    "risk_band",
    "content_count"
]

print("RISK BAND DISTRIBUTION")
display(risk_distribution)


plt.figure(figsize=(7, 5))

plt.bar(
    risk_counts.index,
    risk_counts.values
)

plt.ylabel("Number of content observations")
plt.title("Ranked Content Risk Bands")
plt.tight_layout()

plt.savefig(
    "risk_band_distribution.png",
    dpi=200,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 6. Top 20 ranked recommendations
# ------------------------------------------------------------

top_20 = recommendations[
    [
        "risk_rank",
        "content_hash_id",
        "decline_risk",
        "risk_band",
        "reason_codes",
        "recommended_action"
    ]
].head(20)

print("TOP 20 RANKED RECOMMENDATIONS")
display(top_20)


# ------------------------------------------------------------
# 7. Save tables for the paper
# ------------------------------------------------------------

model_results.to_csv(
    "model_comparison.csv",
    index=False
)

monthly_results.to_csv(
    "monthly_decline_rate.csv",
    index=False
)

risk_distribution.to_csv(
    "risk_band_distribution.csv",
    index=False
)

top_20.to_csv(
    "top_20_recommendations.csv",
    index=False
)

print("All Section 7 artifacts generated successfully.")

"""## 8. Reproducibility

The analysis was developed using Python, DuckDB, pandas, scikit-learn, and matplotlib.

The workflow is organized as a sequence of FlyRank internship notebooks covering task framing, feature construction, leakage checking, modeling, validation, and the final capstone analysis.

The final repository contains the assignment notebooks under `work/notebooks/` together with the capstone notebook and deployment artifacts.

All identifiers used in the analysis are pseudonymized. No client names, domains, private queries, credentials, or raw exports are included in the public-facing paper.

The analysis can be reproduced from the permitted FlyRank internship dataset release using the documented feature construction and validation process.

## 9. Acknowledgments & Data Credit

Built on the FlyRank ML Internship dataset.

The dataset was provided as part of the FlyRank ML Internship program and was used for educational research and decision-support modeling.

Data source: [FlyRank](https://flyrank.ai)

## ML-12 — 5-Minute Demo Outline

### 0:00–0:45 — Research question
Explain the decision: which content should be prioritized for review when resources are limited?

### 0:45–1:30 — Data
Explain the monthly content-level dataset, the 20% decline definition, and the eligible labeled observations.

### 1:30–2:30 — Method
Explain the time-based split, baseline, Logistic Regression, Random Forest, and leakage audit.

### 2:30–3:30 — Results
Show the model comparison and explain that the leakage-safe Random Forest achieved ROC-AUC 0.5554 versus 0.5000 for the baseline.

### 3:30–4:30 — Recommendations
Show the ranked content risk output and explain the reason codes and recommended actions.

### 4:30–5:00 — Limitations
Emphasize that the model provides directional decision support and does not establish causality or prove search-engine algorithm effects.

## ML-12 — Social Post

I built a leakage-safe content decline scoring model using the FlyRank ML Internship search intelligence dataset.

The project aggregates monthly content performance, defines a 20% next-month impression decline, validates models using a time-based split, and ranks content by predicted decline risk.

The final Random Forest achieved a ROC-AUC of 0.5554 compared with 0.5000 for the baseline.

The important lesson was not just model performance. A leakage audit revealed future-dated content fields, so I removed date-derived features before final evaluation.

The result is a directional decision-support workflow for prioritizing content review, not a causal claim about search performance.

## ML-12 — Employer-Facing Summary

I developed an end-to-end search intelligence modeling workflow using a large-scale content performance warehouse. I designed a next-month decline target, built leakage-safe features, used a time-based validation strategy, compared machine-learning models against a baseline, and produced ranked content recommendations with reason codes. The project demonstrates practical skills in data engineering, feature engineering, leakage detection, model validation, and translating model outputs into actionable decision-support recommendations.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.
- [ ] My deployed paper has **all 9 sections** — including the **Abstract** at the top and **Acknowledgments & data credit** (the https://flyrank.ai link) at the bottom.
- [ ] **ML-12 done in this notebook's closing cells:** 5-minute demo outline + a social-post cut + a 3-sentence employer-facing summary.
"""